create table if not exists public.demo_notes (
  id bigint generated by default as identity primary key,
  title text not null,
  inserted_at timestamptz not null default now()
);

alter table public.demo_notes enable row level security;

drop policy if exists "Allow anon read demo_notes" on public.demo_notes;
create policy "Allow anon read demo_notes"
on public.demo_notes
for select
to anon
using (true);

insert into public.demo_notes (title)
values
  ('Local Supabase row 1'),
  ('Local Supabase row 2')
on conflict do nothing;
